### ISSUE TITLE
Error in interpreting describeSensor response json of recent version of 52N SOS 

### ISSUE THREAD

**Issue by ptagliolato** [oscarfonts/sensor-widgets#68]
Found the issue when requesting to a very recent version of 52N SOS the SOS.js throws an error. The json structure is slightly different and the XML previously in response.procedureDescription.description is now directly in response.procedureDescription.
We forked your project (great Job...thanks :) and very little changes at line 35- solved the problem.

**Comment by oscarfonts** [comment]
Paolo,

Last commit should solve it. Couldn't test it, so please confirm it works for you.

Thanks for the feedback!

**Comment by oscarfonts** [comment]
Guess it works
