### ISSUE TITLE
Examples and the Widgets don't work anymore

### ISSUE THREAD

**Issue by sufiankaki** [oscarfonts/sensor-widgets#99]
Looks like the link https://sensors.fonts.cat/js/SensorWidgets.js is broken and hence unable to test and try the widget.

**Comment by oscarfonts** [comment]
There was a major refactoring of the library, now it's on https://sensors.fonts.cat/SensorWidgets.js

**Comment by sufiankaki** [comment]
Thank you so much for that, but I wonder why does this not work? http://bl.ocks.org/oscarfonts/5ad801cf830d421e55eb

Shouldn't the widget get rendered in the top window or when I click Open?
